baseurl = "https://www.roestkbh.dk/"
canonifyurls = false
copyright = "Open Source under the MIT license."
disableKinds = ["404", "taxonomyTerm", "taxonomy"]
enableEmoji = true
googleAnalytics = ""
DefaultContentLanguage = "da"
paginate = 10
relativeurls = false
theme = "startbootstrap-clean-blog"
title = "Røst"
[author]
name = "Røst"
[languages]
[languages.da]
weight = 1
languageName = "Dansk"
[[languages.da.menu.main]]
identifier = "home"
name = "Forside"
url = "/"
weight = 1
[params]
dateform = "Mon, Jan 2, 2006"
description = ""
email = "kontakt@roestkbh.dk"
image = "/uploads/2018/01/09/DSC_0027.jpg"
imagetintgradient = "#000, #0004 25%, #0004 75%, #151515"
instagramcallout = "Tjek vores Instagram"
instagramlink = "https://www.instagram.com/roestcph/"
[[params.social]]
title = "facebook"
url = "https://www.facebook.com/roestcph"
[taxonomies]
category = "categories"
tag = "tags"
