---
pages:
- _index.md
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- type: text
  name: subtitle
  label: Subtitle
  default: ''
- name: image
  label: Image
  type: file
  hidden: false
  default: ''
- name: type
  label: Type
  type: text
  hidden: true
  default: page
