# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.1

    environment:
      # Set the email address to use when commiting to repository
      # Does not need to be a correct email, but you can change it
      - OWNER_EMAIL: nobody@example.com
      
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies (change v-num for cache bust)
      - restore_cache:
          keys:
          - v1.2-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn

      # Store yarn / node cache
      - save_cache:
          key: v1.2-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules

      - run:
          name: Build and push to repository
          command: bash ./Build/circleci_build.sh

      - store_artifacts:
          path: ~/repo/yarn.lock
          destination: yarn.lock

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - content
