---
upload_path: "/hugo/static/uploads/:year:/:month:/:day:"
frontmatter_file_url_template: "/uploads/:year:/:month:/:day:"
body_file_url_template: "/uploads/:year:/:month:/:day:"
new_page_extension: md
auto_deploy: true
admin_path: "/admin"
webhook_url: 
sections:
  events:
    default_front_matter_template: event
version: 0.31.1
